#pragma once

// 避免Windows.h与gRPC之间的宏定义冲突
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#ifndef NOMINMAX
#define NOMINMAX
#endif

// 重新定义Windows宏，避免与gRPC枚举冲突
// 必须在包含任何Windows头文件前定义
#ifdef _WIN32
#define WIN_ERROR_CANCELLED ERROR_CANCELLED
#define WIN_ERROR_ABORTED ERROR_REQUEST_ABORTED
#define WIN_NO_ERROR NO_ERROR
#define WIN_ERROR_INVALID_PARAMETER ERROR_INVALID_PARAMETER
#define WIN_ERROR_NOT_FOUND ERROR_NOT_FOUND
#define WIN_INTERNAL INTERNAL
#define WIN_UNAVAILABLE ERROR_SERVICE_UNAVAILABLE
#define WIN_ALREADY_EXISTS ERROR_ALREADY_EXISTS

#undef ERROR_CANCELLED
#undef ERROR_REQUEST_ABORTED
#undef NO_ERROR
#undef ERROR_INVALID_PARAMETER
#undef ERROR_NOT_FOUND
#undef INTERNAL
#undef ERROR_SERVICE_UNAVAILABLE
#undef ERROR_ALREADY_EXISTS
#endif